version: '3.4'

volumes:
  postgresql-db:
    driver: local

services:
  db:
    restart: always
    image: postgres:15.1
    container_name: pleroma-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 2s
      retries: 40
    environment:
      POSTGRES_USER: pleroma
      POSTGRES_PASSWORD: ${PLEROMA_DB_PASSWORD}
      POSTGRES_DB: pleroma
    volumes:
      - ${PLEROMA_DB_DIR}:/var/lib/postgresql/data
      - ./pgdump:/pgdump
    ports:
      - "5432:5432"
    networks:
      - back-pleroma

  web:
    build: docker/images/otp/.
    #container_name: pleroma_web
    restart: always
    environment:
      MIX_ENV: prod
    ports:
      - '4000:4000'
    volumes:
      - ./data/pleroma/content/uploads:/var/lib/pleroma/uploads
      - ./pl.nagi.fan-custom/static:/var/lib/pleroma/static
      - ./data/pleroma/config:/etc/pleroma:ro
    depends_on:
      db:
        condition: service_healthy
      
    networks:
      - caddy
      - back-pleroma
    labels:
      caddy: ${PLEROMA_HOSTNAME}
      caddy.reverse_proxy: "web:4000"

  soapbox:
    build: docker/images/soapbox/.
    restart: always
    environment:
      PLEROMA_HOSTNAME: ${PLEROMA_HOSTNAME}
      SOAPBOX_HOSTNAME: ${SOAPBOX_HOSTNAME}
    ports: 
      - '4001:80'
    networks:
      - caddy
    labels:
      caddy: ${SOAPBOX_HOSTNAME}
      caddy.0_reverse_proxy: ^(/api|.well-known|nodeinfo|proxy|media|emoji|oauth|favicon.*) "web:4000"
      caddy.1_handle_path: /*
      caddy.1_handle_path.reverse_proxy: "soapbox:4001"

networks:
  caddy:
    external: true
  back-pleroma:
    external: true
